Assignment 7 - Ivan Siat - 3081845

Create a Jupyter notebook that explores the concepts and techniques of PDSH sections 2.02 and 2.03. This could be as easy as copying and pasting changed versions of some of the examples from those sections.

Your intent should be to learn some NumPy concepts, so you should change the examples and try to predict what the output will be. Similar to assignment #1, add a markdown cell with your your prediction of what the output will be, then execute the code cell, and if your prediction is incorrect or you have any other thoughts about it, add another markdown cell that explains.

Your notebook should have 15 code cells exploring different concepts.


NumPy Array Attributes

In [34]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print(x1.ndim)
print(x3.shape)
print(x2.size)

1
(3, 4, 5)
12


x1 ndim will be 1 because it has 1 dimension, x3 shape will be 3,4,5 because that is the shape of each dimension, x2 size is 12 because the size is 3x4

Array Indexing: Accessing Single Elements

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

it will display the array x1

In [10]:
x1[3]

3

it will display the value of index 3 in the array x1

In [11]:
x1[7]

IndexError: index 7 is out of bounds for axis 0 with size 6

out of bounds cause the array is only 0-6 

In [12]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

it will display the multidimensional array x3


Array Slicing: Accessing Subarrays

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[5]

5

gets the value at index 5, which is 5

In [25]:
x2[2, 1]

6

gets the value at row 2, column 1

In [26]:
print(x2[0, :])

[3 5 2 4]


In [ ]:
gets the first row


Subarrays as no-copy views

In [27]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


prints the multidimentional numpy array x2 in rows and columns

Creating copies of arrays

In [29]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


copies the 2x2 row and column of x2

In [19]:

x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

Array Concatenation and Splitting - 
Concatenation of arrays


In [20]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

concatenates the two arrays together

In [21]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


splits array into 3


The Slowness of Loops

In [3]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.04 s ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


i dont know how this works, i assume it calculates the time each loop takes


Introducing UFuncs

In [9]:
x = np.arange(9).reshape((3, 3))
print('before squared')
print(x)
print('after squared')
print(2 ** x)

before squared
[[0 1 2]
 [3 4 5]
 [6 7 8]]
after squared
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


squares each array value


Exploring NumPy's UFuncs - Array arithmetic

In [10]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


various arithmetic equations agains the values of the array


Absolute value

In [11]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

displays the absolute value of the array values


Trigonometric functions

In [12]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


trig functions against the values of the array

Exponents and logarithms

In [13]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


log and exponent functions against the array


Specialized ufuncs

In [14]:

from scipy import special
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

ModuleNotFoundError: No module named 'scipy'

Advanced Ufunc Features - 
Specifying output

In [16]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)


[ 0. 10. 20. 30. 40.]



Aggregates

In [17]:
x = np.arange(1, 6)
np.add.reduce(x)

15

Outer products

In [22]:

x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

Solve TP2.2.1 again, but use a NumPy array to calculate the volume of multiple spheres at once. Write it as a function that takes a NumPy array of sphere radii (radiuses) and returns a NumPy array of calculated volumes.

In [28]:
import math
def np_volume(n):
    print(n)
    x = (4/3) * math.pi * (n**3)
    print(x)
    
test1 = np.arange(1,6)
np_volume(test1)

[1 2 3 4 5]
[  4.1887902   33.51032164 113.09733553 268.08257311 523.5987756 ]


Solve TP2.2.2 again, but use NumPy to solve it for multiple values.

First solve it by creating one NumPy array for each of the values in the original problem:

24.95 40% 3 0.75 60

Then add 2 more books to the order by adding 2 more numbers to each of the NumPy arrays above with these 2 sets of values:

26.95 35% 4 1.00 70

27.95 45% 5 1.25 80

Finally, create a function that accepts 4 iterables named price, discount, shipping_base, shipping_additional, and number_of_copies. The function should use the NumPy code you already wrote to return the total cost of a book order.



In [49]:
price = np.array([24.95, 26.95, 27.95])
discount = np.array([0.40, 0.35, 0.45])
shipping_base = np.array([3, 4 , 5])
shipping_additional = np.array([0.75, 1.00, 1.25])
number_of_copies = np.array([60, 70, 80])

def np_bookorder(pr,dsct,sb,sa,noc):
    book_price = (pr *(1.0-dsct) *noc)
    shipping_total = (noc-1) * sa + sb
    total = book_price + shipping_total
    print('price of books with discount: ', book_price)
    print('price of shipping: ', shipping_total)
    print('order total: ', total)
    
np_bookorder(price,discount,shipping_base,shipping_additional,number_of_copies)


price of books with discount:  [ 898.2   1226.225 1229.8  ]
price of shipping:  [ 47.25  73.   103.75]
order total:  [ 945.45  1299.225 1333.55 ]


Resolve TP7.3 by writing a function that takes k as a parameter (instead of iterating until the last term is 1e-15), uses NumPy to calculate the series quickly, and returns the estimate.
Use %timeit (or similar) to compare the speeds of your earlier solution's function and your new function. To make the comparison fair, you'll need to run the same number of iterations of the summation in each, either by changing your earlier solution's function to print the maximum value of k was when it iterated, or to stop after a specified number of iterations

In [29]:
#from assignment 6
def factorial(n):
    if n == 0:
        return 1 #because factorial of 0 is 1
    else:
        return n * factorial(n-1) #recursive function to compute factorial

def estimate_pi():
    sum = 0
    k = 0
    factor = 2*math.sqrt(2) / 9801 #factor 2*sqrt(2) / 9801 in equation
    
    while True:
        x = factorial(4*k) * (1103 + 26390*k) #top half of equation
        y = factorial(k)**4 * 396**(4*k) #bottom half of equation
        n = factor * (x / y) #summation total times factor
        sum += n #total sum
        
        if n < 1e-15: #if n is less than 10^-15, break while loop
            break
            
        k += 1 #add 1 to k to continue while loop
    print(k)    
    return 1/sum
    

#test case
print(estimate_pi())
print(estimate_pi() == math.pi)

2
3.141592653589793
2
True
